#!/bin/sh
set -e

echo "🚀 Pre-commit checks"

pnpm lint
pnpm tsc --noEmit
cargo clippy --manifest-path=src-tauri/Cargo.toml -- -D warnings
cargo fmt --manifest-path=src-tauri/Cargo.toml -- --check

echo "✅ Pre-commit checks passed"
